### ISSUE TITLE
Figure out tech stack

### ISSUE THREAD

**Issue by xavcochran** [HelixDB/HelixDB#1]
Need to figure out what tech stack to use for the initial release. 

The following things need to be considered (this is not exhaustive): 
- Programming Language(s) to use focussing on maintainability, ease of development, ability to be lightweight, performance.
- Storage Engine focussing on performance and ease of implementation.
- Approach to datasharding and database startup.

### Current info:

- **Language**: Rust, Go, C++, Zig
- **Storage Engine**: RocksDB

#### Rust
| Pros | Cons |
|------|------|
| Memory safety without runtime cost | Can have larger binaries |
| Excellent concurrency model | Steeper learning curve |
| Strong type system (Algebraic Data Types) | Longer compile times |
| Great async support | Younger ecosystem than C++ |
| Growing ecosystem | Some features still maturing |
| Good C/C++ interop | |

#### Go
| Pros | Cons |
|------|------|
| Easy to learn | Garbage Collection (Pauses) |
| Fast compile times | Less control over memory |
| Garbage Collection | Limited Generics |
| Great concurrency model | Not ideal for systems programming |
| Good standard library | |
| Good C interop | |
| Growing ecosystem | |

#### C++
| Pros | Cons |
|------|------|
| Maximum performance control | Manual memory management |
| Mature ecosystem | More prone to bugs |
| Extensive libraries | Complex build systems |
| Proven in databases (Neo4j, Nebula) | Steeper learning curve |
| Direct hardware control | |

#### Zig
| Pros | Cons |
|------|------|
| Manual memory management | Younger ecosystem |
| Simple C integration | Smaller community |
| No hidden allocations | Less libraries |
| Small runtime | Steeper learning curve |
| Great error handling | Less help available |
| Easy to learn | |

#### RocksDB
| Pros | Cons |
|------|------|
| Industry proven | Can Have Complex Tuning |
| High performance | C++ Integration needed |
| Used in many databases | General Purpose |
| Good Documentation | Less control over storage format |

**Comment by willbowden** [comment]
RocksDB docs mention that it's suitable for "up to a few terabytes of data...". Is that something we're happy to work with or would Helix need to be able to store larger databases? Or would the act of data sharding negate the limit of RocksDB?

**Comment by willbowden** [comment]
I vote C++ or Rust for language. 

Also @xavcochran any thoughts on my previous comment?

**Comment by xav-db** [comment]
> RocksDB docs mention that it's suitable for "up to a few terabytes of data...". Is that something we're happy to work with or would Helix need to be able to store larger databases? Or would the act of data sharding negate the limit of RocksDB?

I mean to get started that should be fine because we're not going to be storing that much data and it will be an entire job in itself to make our own implementation of it. We could look into some other options. I know there is levelsdb or we could just firm it and make our own.

After we get an mvp out we could start making our own storage layer that will be optimised for graphs. I think it will be too much of a job to do now personally. I think our focus will be best spent on the graph engine, data sharding and query language.

**Comment by xav-db** [comment]
> I vote C++ or Rust for language. 
> 
> Also @xavcochran any thoughts on my previous comment?

I vote rust personally

**Comment by xav-db** [comment]
We have decided to go with rust as the language of choice using rocks db as the storage layer
